"""
Database Seeding Script for ShieldX SOC
Populates realistic development telemetry, alerts, and system state.
Statistics are NOT hardcoded; they are generated by aggregating these database records.
"""
import os
import sys
from datetime import datetime, timedelta, timezone

# Ensure backend root is on sys.path
SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
BACKEND_DIR = os.path.dirname(SCRIPT_DIR)
if BACKEND_DIR not in sys.path:
    sys.path.insert(0, BACKEND_DIR)

from app.db.init_db import init_db
from app.db.session import SyncSessionLocal
from app.models import (
    Alert,
    TelemetrySnapshot,
    ProtocolDistribution,
    Notification,
)


def seed():
    """Seed the database with realistic security alerts and telemetry records."""
    print("Initializing database tables and baseline schema...")
    init_db()

    session = SyncSessionLocal()
    try:
        now = datetime.now(timezone.utc)

        # ─── 1. SEED ALERTS (14 Realistic Threat Alerts) ───
        # Matching frontend incident queue and threat distribution categories:
        # DDoS (5), C2 (3), Scanning (2), Malware (1), Exploitation (1), Botnet (1), Policy Violation (1) = 14 total alerts
        alerts_data = [
            # 1. Critical Volumetric SYN Surge (Alerts tab top row)
            {
                "alert_id": "alt-ddos-8901",
                "timestamp": now - timedelta(seconds=45),
                "threat_class": "DDOS",
                "attack_classification": "DDOS",
                "severity": "CRITICAL",
                "confidence": 0.98,
                "source_ip": "198.51.100.44",
                "source_port": 54112,
                "destination_ip": "10.240.0.12",
                "destination_port": 443,
                "transport_protocol": "TCP : 443",
                "status": "Mitigated",
                "triage_status": "NEW",
                "model_version": "v3.2.0",
                "detector_model": "Ensemble-Volumetric-SYN-Burst",
                "mitre_technique": "T1498.001",
                "reason": "Abnormal volumetric SYN burst exceeding baseline by 840% with high target convergence.",
                "evidence": {
                    "rule": "Ensemble-Volumetric-SYN-Burst",
                    "tactic": "Impact",
                    "pps_peak": 28400,
                    "target_convergence_ratio": 0.94,
                },
                "trigger_features": {
                    "syn_arrival_rate_pps": 28400,
                    "entropy_ip_distribution": 1.12,
                    "unidirectional_syn_ack_ratio": "Infinity (Rx-Only)",
                },
                "metadata_json": {
                    "dateLabel": "Today",
                    "time_formatted": "05:11:12",
                    "accentColor": "#ef4444",
                    "waveform_bars": [8, 12, 10, 14, 11, 16, 15, 20, 18, 24, 22, 28, 25, 32, 29, 38, 34, 44, 40, 52, 48, 64, 58, 72, 65, 85, 78, 62, 50, 42, 35, 26, 20, 15, 10, 8, 5],
                    "raw_packet_snippet": "[FRAME 0x4891] INGRESS ETH0 -> PASSIVE TAP DIODE\nSRC: 198.51.100.44 | DST: 10.240.0.12\nPROTO: TCP | LEN: 1420 BYTES | TTL: 54\nFLAGS: [SYN] WINDOW: 64240 CHECKSUM: 0x9b41\nHEURISTIC: Reflection pattern confirmed | Threat signature ASN 13335\nAI MODEL CONFIDENCE: 98.0% | MITIGATION: Mitigated",
                    "throughput_peak": "42.8 MB/s",
                },
            },
            # 2. High C2 Beaconing (Alerts tab row 2)
            {
                "alert_id": "alt-c2-4029",
                "timestamp": now - timedelta(minutes=2),
                "threat_class": "C2_BEACONING",
                "attack_classification": "C2_BEACONING",
                "severity": "HIGH",
                "confidence": 0.94,
                "source_ip": "10.240.4.88",
                "source_port": 49822,
                "destination_ip": "203.0.113.195",
                "destination_port": 8443,
                "transport_protocol": "HTTPS : 8443",
                "status": "Blocked",
                "triage_status": "INVESTIGATING",
                "model_version": "v2.1.0",
                "detector_model": "LSTM-Interval-Beacon-Detector",
                "mitre_technique": "T1071.001",
                "reason": "Periodic beaconing rhythm detected to high-risk external AS with jitter < 2.4%.",
                "evidence": {
                    "rule": "LSTM-Interval-Beacon-Detector",
                    "tactic": "Command and Control",
                    "periodicity_score": 0.962,
                },
                "trigger_features": {
                    "interval_mean_sec": 45.2,
                    "interval_jitter_std": 0.08,
                    "payload_entropy": 7.84,
                },
                "metadata_json": {
                    "dateLabel": "Today",
                    "time_formatted": "05:09:57",
                    "accentColor": "#f97316",
                    "waveform_bars": [10, 14, 18, 22, 26, 30, 28, 24, 20, 18, 15, 12, 16, 22, 28, 34, 40, 36, 30, 24, 20, 16, 22, 28, 34, 38, 32, 26, 20, 14, 10, 8, 6, 5],
                    "raw_packet_snippet": "[FRAME 0x2A19] INGRESS ETH0 -> PASSIVE TAP DIODE\nSRC: 10.240.4.88 | DST: 203.0.113.195\nPROTO: TLS 1.3 | LEN: 512 BYTES | CADENCE: 45.2s\nSUSPECTED FRAMEWORK: Cobalt Strike / Sliver\nACTION: Blocked at boundary",
                    "throughput_peak": "1.2 MB/s",
                },
            },
            # 3. Medium DGA DNS Tunnel (Alerts tab row 3)
            {
                "alert_id": "alt-dns-6184",
                "timestamp": now - timedelta(minutes=5),
                "threat_class": "DGA_DNS_TUNNEL",
                "attack_classification": "DGA_DNS_TUNNEL",
                "severity": "MEDIUM",
                "confidence": 0.89,
                "source_ip": "10.240.1.19",
                "source_port": 53551,
                "destination_ip": "10.240.0.53",
                "destination_port": 53,
                "transport_protocol": "DNS : 53",
                "status": "Alerted",
                "triage_status": "NEW",
                "model_version": "v2.4.0",
                "detector_model": "Entropy-DGA-Classifier-v2",
                "mitre_technique": "T1071.004",
                "reason": "High frequency TXT/NULL query sequences with anomalous Shannon domain entropy.",
                "evidence": {
                    "rule": "Entropy-DGA-Classifier-v2",
                    "tactic": "Exfiltration",
                    "entropy": 4.62,
                },
                "trigger_features": {
                    "domain_entropy": 4.62,
                    "txt_record_ratio": 0.78,
                    "nxdomain_burst_count": 312,
                },
                "metadata_json": {
                    "dateLabel": "Today",
                    "time_formatted": "05:06:17",
                    "accentColor": "#eab308",
                    "waveform_bars": [5, 8, 12, 15, 20, 25, 30, 35, 40, 45, 40, 35, 30, 25, 20, 15, 12, 10, 8, 6, 5],
                    "raw_packet_snippet": "[FRAME 0x110B] INGRESS ETH0 -> PASSIVE TAP DIODE\nSRC: 10.240.1.19 | DST: 10.240.0.53\nPROTO: DNS QUERY [TXT] | LEN: 240 BYTES\nFQDN: x9j2m10v8z4q7l.tunnel.ns1.darknet.cc\nSHANNON ENTROPY: 4.62 bits | ACTION: Alerted",
                    "throughput_peak": "26.7 MB",
                },
            },
            # 4. Low Flow Anomaly (Alerts tab row 4)
            {
                "alert_id": "alt-anom-1102",
                "timestamp": now - timedelta(minutes=15),
                "threat_class": "ANOMALY",
                "attack_classification": "ANOMALY",
                "severity": "LOW",
                "confidence": 0.72,
                "source_ip": "10.240.2.105",
                "source_port": 41200,
                "destination_ip": "10.240.0.8",
                "destination_port": 22,
                "transport_protocol": "TCP : 8080",
                "status": "Monitored",
                "triage_status": "RESOLVED",
                "model_version": "v1.8.0",
                "detector_model": "IsolationForest-Flow-Anomaly",
                "mitre_technique": "T1046",
                "reason": "Subtle packet size deviation across non-standard port range outside baseline operating hours.",
                "evidence": {
                    "rule": "IsolationForest-Flow-Anomaly",
                    "tactic": "Discovery",
                },
                "trigger_features": {
                    "flow_byte_skewness": 2.14,
                    "unusual_port_frequency": 0.35,
                    "duration_sec": 14.8,
                },
                "metadata_json": {
                    "dateLabel": "Today",
                    "time_formatted": "04:56:57",
                    "accentColor": "#10b981",
                    "waveform_bars": [4, 6, 8, 10, 12, 14, 12, 10, 8, 6, 4],
                    "raw_packet_snippet": "[FRAME 0x098F] INGRESS ETH0 -> PASSIVE TAP DIODE\nSRC: 10.240.2.105 | DST: 10.240.0.8:22\nPROTO: TCP SYN SCAN | DURATION: 14.8s\nACTION: Resolved / Monitored",
                    "throughput_peak": "4.8 KB/s",
                },
            },
            # 5. Additional Critical DDoS (UDP Amplification)
            {
                "alert_id": "INC-8891",
                "timestamp": now - timedelta(minutes=3),
                "threat_class": "DDOS",
                "attack_classification": "DDoS (Reflection)",
                "severity": "CRITICAL",
                "confidence": 0.92,
                "source_ip": "203.0.113.45",
                "source_port": 11211,
                "destination_ip": "10.0.0.12",
                "destination_port": 443,
                "transport_protocol": "UDP : 443",
                "status": "Mitigated",
                "triage_status": "NEW",
                "model_version": "v3.2.0",
                "detector_model": "Memcached-UDP-Reflection-Detector",
                "mitre_technique": "T1498.002",
                "reason": "High-amplification inbound UDP reflection flood against port 443.",
                "evidence": {"amplification_factor": 52.4},
                "trigger_features": {"packet_rate": 31200, "amplification": "52x"},
                "metadata_json": {"time_formatted": "14:24:17", "bytes": "42.8 MB/s"},
            },
            # 6. Additional High C2 Beacon
            {
                "alert_id": "INC-8890",
                "timestamp": now - timedelta(minutes=6),
                "threat_class": "C2_BEACONING",
                "attack_classification": "C2 Communication",
                "severity": "HIGH",
                "confidence": 0.87,
                "source_ip": "185.199.110.23",
                "source_port": 50124,
                "destination_ip": "10.0.0.12",
                "destination_port": 8443,
                "transport_protocol": "TCP : 8443",
                "status": "Blocked",
                "triage_status": "INVESTIGATING",
                "model_version": "v2.1.0",
                "detector_model": "IsolationForest-C2-Jitter",
                "mitre_technique": "T1071.001",
                "reason": "Recurrent session handshake with minimal jitter to known malicious external ASN.",
                "evidence": {"jitter_pct": 2.1},
                "trigger_features": {"interval_mean_sec": 60.1, "jitter_pct": 2.1},
                "metadata_json": {"time_formatted": "14:22:03", "bytes": "1.2 MB/s"},
            },
            # 7. Port Scanning Alert
            {
                "alert_id": "INC-8889",
                "timestamp": now - timedelta(minutes=9),
                "threat_class": "SCANNING",
                "attack_classification": "Port Scanning",
                "severity": "HIGH",
                "confidence": 0.81,
                "source_ip": "92.38.148.77",
                "source_port": 39100,
                "destination_ip": "10.0.0.25",
                "destination_port": None,
                "transport_protocol": "TCP : 1-65535 Sweep",
                "status": "Blocked",
                "triage_status": "INVESTIGATING",
                "model_version": "v1.4.0",
                "detector_model": "Fast-Syn-Scanner-Detector",
                "mitre_technique": "T1046",
                "reason": "Rapid horizontal port sweep scanning ports 1-1024 within 3.2 seconds.",
                "evidence": {"scanned_ports_count": 1024},
                "trigger_features": {"ports_per_sec": 320, "syn_only": True},
                "metadata_json": {"time_formatted": "14:18:45", "bytes": "340 KB/s"},
            },
            # 8. Exploitation Attempt
            {
                "alert_id": "INC-8888",
                "timestamp": now - timedelta(minutes=12),
                "threat_class": "EXPLOITATION",
                "attack_classification": "Exploitation Attempt",
                "severity": "MEDIUM",
                "confidence": 0.76,
                "source_ip": "45.132.23.11",
                "source_port": 44102,
                "destination_ip": "10.0.0.18",
                "destination_port": 22,
                "transport_protocol": "TCP : 22",
                "status": "Alerted",
                "triage_status": "NEW",
                "model_version": "v2.0.0",
                "detector_model": "Signature-Exploit-Matcher",
                "mitre_technique": "T1190",
                "reason": "Anomalous SSH protocol banner exchange matching CVE-2024-3094 probing pattern.",
                "evidence": {"cve": "CVE-2024-3094"},
                "trigger_features": {"ssh_banner_mismatch": True},
                "metadata_json": {"time_formatted": "14:16:11", "bytes": "4.8 KB/s"},
            },
            # 9. Reconnaissance / ICMP Sweep (Scanning)
            {
                "alert_id": "INC-8887",
                "timestamp": now - timedelta(minutes=16),
                "threat_class": "SCANNING",
                "attack_classification": "Reconnaissance",
                "severity": "MEDIUM",
                "confidence": 0.71,
                "source_ip": "198.51.100.27",
                "source_port": None,
                "destination_ip": "10.0.0.31",
                "destination_port": None,
                "transport_protocol": "ICMP : Echo",
                "status": "Monitored",
                "triage_status": "RESOLVED",
                "model_version": "v1.2.0",
                "detector_model": "ICMP-Sweep-Detector",
                "mitre_technique": "T1595.002",
                "reason": "Sequential ICMP echo request bursts across internal /24 subnet range.",
                "evidence": {"icmp_qps": 850},
                "trigger_features": {"probed_subnets": "10.0.0.0/24"},
                "metadata_json": {"time_formatted": "14:12:09", "bytes": "850 B/s"},
            },
            # 10. Malware Signature Match
            {
                "alert_id": "alt-mal-9901",
                "timestamp": now - timedelta(minutes=18),
                "threat_class": "MALWARE",
                "attack_classification": "Malware Ingress",
                "severity": "HIGH",
                "confidence": 0.78,
                "source_ip": "10.0.0.12",
                "source_port": 58912,
                "destination_ip": "194.26.29.112",
                "destination_port": 80,
                "transport_protocol": "HTTP : 80",
                "status": "Blocked",
                "triage_status": "INVESTIGATING",
                "model_version": "v3.1.0",
                "detector_model": "Yara-Memory-Payload-Classifier",
                "mitre_technique": "T1204.002",
                "reason": "Uncompressed executable binary payload hash matching known loader dropper signature.",
                "evidence": {"sha256": "3a7b8e1f..."},
                "trigger_features": {"entropy": 6.88, "mz_header": True},
                "metadata_json": {"time_formatted": "14:20:14", "bytes": "2.4 MB"},
            },
            # 11. Botnet Activity
            {
                "alert_id": "alt-bot-7721",
                "timestamp": now - timedelta(minutes=24),
                "threat_class": "BOTNET",
                "attack_classification": "Botnet Activity",
                "severity": "MEDIUM",
                "confidence": 0.73,
                "source_ip": "198.51.100.27",
                "source_port": 34112,
                "destination_ip": "10.240.0.12",
                "destination_port": 443,
                "transport_protocol": "TCP : 443",
                "status": "Monitored",
                "triage_status": "NEW",
                "model_version": "v1.9.0",
                "detector_model": "Mirai-Cluster-Classifier",
                "mitre_technique": "T1584.005",
                "reason": "Synchronized session initiation rate characteristic of infected Mirai/Gafgyt botnet nodes.",
                "evidence": {"botnet_family": "Mirai"},
                "trigger_features": {"concurrent_syn_sources": 84},
                "metadata_json": {"time_formatted": "14:14:33", "bytes": "120 KB/s"},
            },
            # 12. Policy Violation
            {
                "alert_id": "alt-pol-3321",
                "timestamp": now - timedelta(minutes=28),
                "threat_class": "POLICY_VIOLATION",
                "attack_classification": "Policy Violation",
                "severity": "LOW",
                "confidence": 0.68,
                "source_ip": "10.240.2.14",
                "source_port": 51230,
                "destination_ip": "8.8.8.8",
                "destination_port": 53,
                "transport_protocol": "UDP : 53",
                "status": "Monitored",
                "triage_status": "RESOLVED",
                "model_version": "v1.0.0",
                "detector_model": "Enclave-Egress-Policy-Checker",
                "mitre_technique": "T1071",
                "reason": "Direct DNS query bypassing internal authorized enterprise recursive resolvers.",
                "evidence": {"unauthorized_dns": True},
                "trigger_features": {"bypassed_resolver": "8.8.8.8"},
                "metadata_json": {"time_formatted": "14:08:12", "bytes": "120 B/s"},
            },
            # 13. Additional DDoS (SYN Flood)
            {
                "alert_id": "alt-ddos-8902",
                "timestamp": now - timedelta(minutes=32),
                "threat_class": "DDOS",
                "attack_classification": "DDOS",
                "severity": "CRITICAL",
                "confidence": 0.95,
                "source_ip": "198.51.100.89",
                "source_port": 49112,
                "destination_ip": "10.240.0.12",
                "destination_port": 443,
                "transport_protocol": "TCP : 443",
                "status": "Mitigated",
                "triage_status": "RESOLVED",
                "model_version": "v3.2.0",
                "detector_model": "Ensemble-Volumetric-SYN-Burst",
                "mitre_technique": "T1498.001",
                "reason": "Prior resolved volumetric burst spike absorbed by upstream scrubbing.",
                "evidence": {"syn_rate": 21000},
                "trigger_features": {"syn_arrival_rate_pps": 21000},
                "metadata_json": {"time_formatted": "13:58:00", "bytes": "32.1 MB/s"},
            },
            # 14. Additional DDoS (ICMP Flood)
            {
                "alert_id": "alt-ddos-8903",
                "timestamp": now - timedelta(minutes=45),
                "threat_class": "DDOS",
                "attack_classification": "DDOS",
                "severity": "HIGH",
                "confidence": 0.88,
                "source_ip": "203.0.113.11",
                "source_port": None,
                "destination_ip": "10.240.0.12",
                "destination_port": None,
                "transport_protocol": "ICMP",
                "status": "Mitigated",
                "triage_status": "RESOLVED",
                "model_version": "v2.2.0",
                "detector_model": "ICMP-Volumetric-Flood-Detector",
                "mitre_technique": "T1498.001",
                "reason": "ICMP payload volumetric saturation across ingress interface.",
                "evidence": {"pps": 18200},
                "trigger_features": {"icmp_rate": 18200},
                "metadata_json": {"time_formatted": "13:42:15", "bytes": "15.4 MB/s"},
            },
        ]

        # Insert alerts if not existing
        inserted_alerts = 0
        for ad in alerts_data:
            existing = session.get(Alert, ad["alert_id"])
            if not existing:
                alert_obj = Alert(**ad)
                session.add(alert_obj)
                inserted_alerts += 1
        session.commit()
        print(f"-> Seeded {inserted_alerts} new alert records into 'alerts' table.")

        # ─── 2. SEED TELEMETRY SNAPSHOTS & PROTOCOLS ───
        # Create rolling snapshots for 15 min, 1 hour, etc.
        snapshot = TelemetrySnapshot(
            timestamp=now,
            packets_per_sec=54200.0,
            bytes_per_sec=53500000.0,  # ~428 Mbps
            active_flows_count=14820,
            threat_alerts_count=14,
            threat_alerts_critical=3,
            detection_latency_ms=740.0,
            actual_egress_packets=0,
            actual_egress_bytes=0,
            sliding_window_sec=10.0,
            flow_asymmetry_index=1.0,
            dns_qps=1840.0,
            dns_surge_pct=18.0,
            is_anomaly=False,
        )
        session.add(snapshot)
        session.flush()

        protocols_data = [
            {"protocol_name": "TCP", "packet_count": 320000, "byte_count": 380000000, "bandwidth_pct": 68.5, "dot_color": "#2563eb"},
            {"protocol_name": "UDP", "packet_count": 140000, "byte_count": 110000000, "bandwidth_pct": 21.2, "dot_color": "#00d2ff"},
            {"protocol_name": "DNS", "packet_count": 48000, "byte_count": 28000000, "bandwidth_pct": 7.8, "dot_color": "#a855f7"},
            {"protocol_name": "ICMP", "packet_count": 12000, "byte_count": 6000000, "bandwidth_pct": 2.5, "dot_color": "#f59e0b"},
        ]
        for p in protocols_data:
            proto_obj = ProtocolDistribution(
                snapshot_id=snapshot.id,
                timestamp=now,
                **p
            )
            session.add(proto_obj)
        session.commit()
        print(f"-> Seeded telemetry snapshot ID {snapshot.id} with 4 protocol breakdowns.")

        # ─── 3. SEED OPERATOR NOTIFICATIONS ───
        notifications_data = [
            {"alert_id": "alt-ddos-8901", "title": "Critical DDoS Incident", "level": "critical", "description": "Inbound UDP spike on port 443 exceeding threshold", "time_label": "2m ago"},
            {"alert_id": "alt-c2-4029", "title": "Suspicious C2 Beacon", "level": "high", "description": "Outbound DNS anomaly detected with low jitter", "time_label": "14m ago"},
            {"alert_id": "INC-8889", "title": "Port Scan Flagged", "level": "medium", "description": "Originating from 92.38.148.77 across ports 1-1024", "time_label": "28m ago"},
        ]
        for n in notifications_data:
            notif = Notification(**n)
            session.add(notif)
        session.commit()
        print(f"-> Seeded {len(notifications_data)} notifications in notifications queue.")

        print("\nAll database seeding operations successfully completed!")

    except Exception as e:
        session.rollback()
        print(f"Error during seeding: {e}", file=sys.stderr)
        raise
    finally:
        session.close()


if __name__ == "__main__":
    seed()
