/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ConsoleRouteImport } from './routes/console'
import { Route as ConsoleIndexRouteImport } from './routes/console.index'
import { Route as ConsoleDetectorsRouteImport } from './routes/console.detectors'
import { Route as ConsoleIncidentsRouteImport } from './routes/console.incidents'
import { Route as ConsoleSystemRouteImport } from './routes/console.system'
import { Route as ConsoleTrafficRouteImport } from './routes/console.traffic'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ConsoleRoute = ConsoleRouteImport.update({
  id: '/console',
  path: '/console',
  getParentRoute: () => rootRouteImport,
} as any)
const ConsoleIndexRoute = ConsoleIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ConsoleRoute,
} as any)
const ConsoleDetectorsRoute = ConsoleDetectorsRouteImport.update({
  id: '/detectors',
  path: '/detectors',
  getParentRoute: () => ConsoleRoute,
} as any)
const ConsoleIncidentsRoute = ConsoleIncidentsRouteImport.update({
  id: '/incidents',
  path: '/incidents',
  getParentRoute: () => ConsoleRoute,
} as any)
const ConsoleSystemRoute = ConsoleSystemRouteImport.update({
  id: '/system',
  path: '/system',
  getParentRoute: () => ConsoleRoute,
} as any)
const ConsoleTrafficRoute = ConsoleTrafficRouteImport.update({
  id: '/traffic',
  path: '/traffic',
  getParentRoute: () => ConsoleRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/console': typeof ConsoleRouteWithChildren
  '/console/detectors': typeof ConsoleDetectorsRoute
  '/console/incidents': typeof ConsoleIncidentsRoute
  '/console/system': typeof ConsoleSystemRoute
  '/console/traffic': typeof ConsoleTrafficRoute
  '/console/': typeof ConsoleIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/console/detectors': typeof ConsoleDetectorsRoute
  '/console/incidents': typeof ConsoleIncidentsRoute
  '/console/system': typeof ConsoleSystemRoute
  '/console/traffic': typeof ConsoleTrafficRoute
  '/console': typeof ConsoleIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/console': typeof ConsoleRouteWithChildren
  '/console/detectors': typeof ConsoleDetectorsRoute
  '/console/incidents': typeof ConsoleIncidentsRoute
  '/console/system': typeof ConsoleSystemRoute
  '/console/traffic': typeof ConsoleTrafficRoute
  '/console/': typeof ConsoleIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/console'
    | '/console/detectors'
    | '/console/incidents'
    | '/console/system'
    | '/console/traffic'
    | '/console/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/console/detectors'
    | '/console/incidents'
    | '/console/system'
    | '/console/traffic'
    | '/console'
  id:
    | '__root__'
    | '/'
    | '/console'
    | '/console/detectors'
    | '/console/incidents'
    | '/console/system'
    | '/console/traffic'
    | '/console/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ConsoleRoute: typeof ConsoleRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/console': {
      id: '/console'
      path: '/console'
      fullPath: '/console'
      preLoaderRoute: typeof ConsoleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/console/': {
      id: '/console/'
      path: '/'
      fullPath: '/console/'
      preLoaderRoute: typeof ConsoleIndexRouteImport
      parentRoute: typeof ConsoleRoute
    }
    '/console/detectors': {
      id: '/console/detectors'
      path: '/detectors'
      fullPath: '/console/detectors'
      preLoaderRoute: typeof ConsoleDetectorsRouteImport
      parentRoute: typeof ConsoleRoute
    }
    '/console/incidents': {
      id: '/console/incidents'
      path: '/incidents'
      fullPath: '/console/incidents'
      preLoaderRoute: typeof ConsoleIncidentsRouteImport
      parentRoute: typeof ConsoleRoute
    }
    '/console/system': {
      id: '/console/system'
      path: '/system'
      fullPath: '/console/system'
      preLoaderRoute: typeof ConsoleSystemRouteImport
      parentRoute: typeof ConsoleRoute
    }
    '/console/traffic': {
      id: '/console/traffic'
      path: '/traffic'
      fullPath: '/console/traffic'
      preLoaderRoute: typeof ConsoleTrafficRouteImport
      parentRoute: typeof ConsoleRoute
    }
  }
}

interface ConsoleRouteChildren {
  ConsoleDetectorsRoute: typeof ConsoleDetectorsRoute
  ConsoleIncidentsRoute: typeof ConsoleIncidentsRoute
  ConsoleSystemRoute: typeof ConsoleSystemRoute
  ConsoleTrafficRoute: typeof ConsoleTrafficRoute
  ConsoleIndexRoute: typeof ConsoleIndexRoute
}

const ConsoleRouteChildren: ConsoleRouteChildren = {
  ConsoleDetectorsRoute: ConsoleDetectorsRoute,
  ConsoleIncidentsRoute: ConsoleIncidentsRoute,
  ConsoleSystemRoute: ConsoleSystemRoute,
  ConsoleTrafficRoute: ConsoleTrafficRoute,
  ConsoleIndexRoute: ConsoleIndexRoute,
}

const ConsoleRouteWithChildren =
  ConsoleRoute._addFileChildren(ConsoleRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ConsoleRoute: ConsoleRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
